### ISSUE TITLE
Vanilla igloo floor with basement generated above terrain.

### ISSUE THREAD

**Issue by alexander4308** [Builderb0y/BigGlobe#11]
I tried to find any information about this bug, but i failed. It is generated above the ground at the middle of the hill.
So i suggest to keep an eye on any flying structures.

**Comment by Builderb0y** [comment]
Igloos look fine to me, including ones with and without basements. Can you give the world seed + coordinates of an igloo with this issue, along with a screenshot of the issue? A log file might also help.

**Comment by alexander4308** [comment]
Found another one
![{9BADFA26-59B5-4A7E-B0E0-84B4ED2B37F2}](https://github.com/user-attachments/assets/e4b39653-d78c-4fb4-9402-e1b13ae44b73)

**Comment by Builderb0y** [comment]
Oh, it spawned in a lake. That explains it. What's happening here is that the igloo tries to position itself on the surface, but it doesn't know there's a lake there. Meanwhile, the lake decreases the Y level of terrain around it, without knowing there's an igloo there. The net result is that the igloo spawns where the surface *would* have been if the lake hadn't been there, which is a higher Y level than with the lake there. The igloo also tries to flatten the ground around it so that it's not floating, but the lake probably decreases the Y level *afterwards*, which negates that effect.

There is not much I can do about this, since minecraft doesn't have any good systems in place to make structures avoid spawning on top of each other. The only system minecraft has to avoid structure collisions *at all* is not good, as it's prone to crashing if used incorrectly, and only works for structures that are on the surface. Underground structure collisions can cause problems too.

Maybe what I could do is make lakes decrease the surface Y level first, before any other structures try to spawn. The igloo still wouldn't know about the lake, and would try to spawn higher, but it would also manipulate the surface after the lake does, and hopefully be on flat ground again. You might see an ugly hill in the middle of a lake when this happens, but at least the igloo wouldn't be floating mid-air anymore. I will try this.

**Comment by Builderb0y** [comment]
I'm not sure if this is an improvement or not, but this is what it looks like when lakes decrease the surface Y level first, before igloos do anything.
![image](https://github.com/user-attachments/assets/26d96100-fb08-4daf-a4df-e17e610d7868)

**Comment by alexander4308** [comment]
Shouldn't be a problem since you've got the custom chunk generator?

**Comment by Builderb0y** [comment]
Having a custom chunk generator doesn't automatically mean everything is easy to make work without bugs. There's still a lot of things I don't have control over, and this is one of them. Minecraft's structure placement logic is something that has caused a lot of annoyances for me in the past, so believe me when I say if there was an easy way to make structures behave themselves and stop colliding with each other, I'd've done that by now.

**Comment by alexander4308** [comment]
This igloo facing at?
![{5929A508-4DF1-42D6-832E-871117AE9FD6}](https://github.com/user-attachments/assets/89bb26fa-0873-4c5e-be30-3e8f51258bbc)

**Comment by Builderb0y** [comment]
Uh... huh. Not sure why it looks cut-off like that, but I did fix the terrain being too high just now.
![image](https://github.com/user-attachments/assets/7166be95-f01f-4c5b-bcda-a42734edbdf1)

**Comment by Builderb0y** [comment]
Improved somewhat in V4.4.0.
