### ISSUE TITLE
Update information about recommended mod list

### ISSUE THREAD

**Issue by alexander4308** [Builderb0y/BigGlobe#12]
I am asking to add RelativityMC mods such as ScalableLux, the Starlight fork as it is reducing light bottleneck by paralleling the light operations, which is also speedups the worldgen by noticeable amount.
Also, please, reconsider opinion on C2ME, because it is not only about speeding up worldgen, but making the chunk system more responsive in general. It is pretty modular and you can turn off some modules for compatibility.

**Comment by Builderb0y** [comment]
Having now tested both, I can say that while my CPU was being utilized significantly better, this did not result in a noticeable speedup for me, which is weird. It was also difficult to profile properly because both mods move stuff to different threads, making it hard to compare the old timing data to the new timing data. A very rough approximation would suggest that ScalableLux may have made lighting logic 10x faster, but lighting only accounted for about 10% of total time spent by Minecraft's worker threads to begin with, so it wasn't a huge bottleneck for me. Your results may vary.

I have updated the description on Modrinth to put ScalableLux with the other optimization mods that are recommended, and re-categorized C2ME as "neither recommended nor discouraged". I also indicated that it might improve chunk generation speed for some people. Is this sufficient?

**Comment by alexander4308** [comment]
C2ME is also smooths MSPT. Also here is some results from feature/dfc0 branch of C2ME with some tweaks enabled in order to load 13900k fully.
[vanilla.log](https://github.com/user-attachments/files/17071614/vanilla.log)
[relativitymc.log](https://github.com/user-attachments/files/17071615/relativitymc.log)

**Comment by Builderb0y** [comment]
Sure enough, MSPT is lower with C2ME while doing worldgen. I didn't test that before. Modrinth description has been updated again. Is there anything else C2ME helps with that I didn't test yet?

**Comment by alexander4308** [comment]
Thanks. That is enough.
