### ISSUE TITLE
[Request] Cobblemon spawning support.

### ISSUE THREAD

**Issue by Dolyfin** [Builderb0y/BigGlobe#26]
Cobblemon appears to support spawning if there is properly tagged biomes. 
Such as: https://github.com/Stardust-Labs-MC/Terralith/tree/1.20/data/forge/tags/worldgen/biome
And: https://wiki.cobblemon.com/index.php/Pokémon/Spawning/Spawn_Definitions

Would love to see support for using it with Cobblemon. Tried in 1.20.1 and snapshot 1.21.1 cobblemon versions.

**Comment by Builderb0y** [comment]
My biomes can be added to tags via data packs. I do not add my biomes to vanilla or common tags by default because lots of other worldgen mods use that to decide where they can place their structures, and more often than not, said structures spawn in hilariously out-of-place locations. Mid-air dungeons, ocean monuments with one corner in a river and the rest on dry land, you name it.

Ideally, I want all mod integration to be opt-in and handled entirely by a data pack. And as someone who has never played pokemon before, I don't really want to be in charge of making a data pack for cobblemon. But you can. Adding biomes to tags with a data pack is really easy.

**Comment by Dolyfin** [comment]
Thank you for your response. I've looked more into Cobblemon datapacks and it does seem like I could add Big Globe biomes into existing categories. 

I'll see if I can create this myself.
