### ISSUE TITLE
Mob Spawning/Mob cap is not reached.

### ISSUE THREAD

**Issue by Nimjam** [Builderb0y/BigGlobe#41]
I tried to build a Creeper farm over an ocean but there were barely spawning in any creepers so I tried a normal mob farm and got the same result. When I tried to build these exact farms in minecraft:plains (Superflat) the rate was way higher. I used the minihud mod to determine if there could be a space where the mobs could spawn outside the farms but there wasnt a single space. So only 7-20 out of 70 mobs spawned in.

**Comment by Builderb0y** [comment]
When minecraft tries to spawn mobs, it picks a random Y level between the bottom of the world and the surface. Since big globe worlds are vastly taller than vanilla worlds, there are a lot more Y levels it could choose that are outside the range that's near you, and this reduces the overall spawn rate. If you're killing mobs shortly after they spawn, the spawn cap might not have time to be reached.

This isn't a bug in big globe, it's just how minecraft's spawning logic works. And I think changing this part of mob spawning logic is outside the scope of big globe.

**Comment by Builderb0y** [comment]
So... I took another look at that logic, and while most things related to mob spawning are quite complicated, this part in particular turned out to be really easy to change. So in the next version of big globe, I'll add a way to spawn more mobs in taller worlds. It'll be disabled by default and require manually enabling in the mixin config file, but it'll be there for anyone who wants it.

**Comment by Builderb0y** [comment]
The next version has been released. Set `SpawnHelper_MoreMobsInTallerWorlds` to true inside `.minecraft/config/bigglobe/mixins.properties` to have more mobs in taller worlds.
