### ISSUE TITLE
Height limit issue with nether bedrock 

### ISSUE THREAD

**Issue by xssmusashi** [Builderb0y/BigGlobe#46]
Hey! Your mod is one of the best I’ve found, but I’ve run into an issue. 
I’m trying to build a XP farm, and I need to construct something above the bedrock in the Nether, but the height limit for building is 1023. 
Is there any way to remove this limit? Or maybe it’s possible to increase the limit by 100-200 blocks?

**Comment by Builderb0y** [comment]
You can probably do that with a data pack that just tweaks the dimension type, but I've never tested what happens when that doesn't match the generator height. So be warned it might behave weirdly in cases that I can't predict. You can also just build it above the lava ocean. There's plenty of space there too.

**Comment by xssmusashi** [comment]
The thing is, I need to do this specifically above the bedrock.
Is it possible to use such a datapack on a Fabric server? With an already created world, of course.
And maybe you could suggest a datapack that would be suitable for things like this?

Also, in general, it would be cool to configure the build height through a configuration file, but that's just wishful thinking :)

**Comment by Builderb0y** [comment]
I don't think you understand what you're asking for here. The dimension type controls how tall the chunks minecraft creates are, and minecraft does not allow you to have different chunks in the same world with different heights. If the dimension type height does not match the region file data, results are undefined. You might get minecraft to use whatever sections it can, you might get minecraft to ignore the existing sections and re-generate the chunk from scratch, you might get the entire generated chunk area to just be full of air, or you might flat out crash. I take no responsibility for any corruption or loss of data that might occur while trying to re-size an existing dimension.

With that in mind, to answer the rest of your questions:
* Data packs work just as well on servers as they do on clients.
* Make a backup before trying to re-size an existing dimension, or delete the nether before resizing and let it regenerate.
* I don't have a data pack specifically designed for this already because I didn't expect this to be something people would want to do.
* Injecting config options into data pack loading is not worth the effort, and has no benefits over just overriding the files with another data pack.

**Comment by xssmusashi** [comment]
Thank you so much for your reply!
