### ISSUE TITLE
tutorial for adding structure mod support

### ISSUE THREAD

**Issue by ryleu** [Builderb0y/BigGlobe#53]
Love the mod, just trying to get ChoiceTheorem's Overhauled Villages mod to work properly with BG. Are there any plans in the works for writing instructions on adding structures to BG? Thanks!

**Comment by ChoiceTheorem** [comment]
After inspecting this mod's code, I conclude that the developers have to add their biomes to Minecraft default biome tags properly. If the dev doesn't patch this by Christmas, I'll make a pull request to this mod.

**Comment by ryleu** [comment]
I believe that would break BG. You can certainly try it, but by my understanding of how this mod works, I think that would make a bunch of structures spawn twice or otherwise be incorrect.

**Comment by ChoiceTheorem** [comment]
Oh wait, the compat datapack is in the discord server.

**Comment by Builderb0y** [comment]
My biomes are intentionally not in vanilla tags *specifically* to prevent other mods from making the assumption that they can generate structures in them. Most of the time, other mods' structures (and some vanilla structures) spawn in wildly inappropriate places by default. I've seen dungeons and trial chambers floating in mid-air, modded ocean monuments with one corner in a river and the rest on dry land, *vanilla* ocean monuments spawning above sea level and encasing themselves in a massive cube of water, honestly you name it.

The intended way to allow other mods to generate structures in big globe worlds is to use a data pack to add big globe's biomes to the structure's biome tag, and possibly also create a structure overrider script that can correct for inappropriate spawning locations, or abort the structure entirely if the spawn location cannot be corrected solely by moving it vertically. This ensures that manual human effort has been put into making the structure spawn correctly, and users do not need to rely on often-broken hard-coded logic that simply wasn't designed with big globe worlds in mind when it was written.

Some mods' structures don't have their own biome tag and directly specify a vanilla tag instead of making their own tag which includes the vanilla tag. For these structures, I have the "delegating" structure type, which allows data packs to define structures that are identical to another structure, but use a different biome tag. Delegating structures can also override the mobs that spawn in the structure, along with the generation step and terrain adaptation.

There are also a few modded structures I've seen which don't override `StructurePiece.translate()` to update their internal state correctly (vanilla ocean monuments also fail to do this), and look broken when a structure overrider script attempts to move them. Such modded structures are out of scope for me to support. I have a mixin to fix vanilla ocean monuments.

The last thing I will note here is that I don't know how much of the above text applies to CTOV specifically. I don't know if it would've spawned badly without an overrider script, I don't know if it specifies a vanilla tag instead of its own tag, and I don't know if it handles being moved correctly. I'm more just talking in general here for some of the other structures that I have seen.

**Comment by Builderb0y** [comment]
I have now finally written a tutorial for adding other mods' structures to big globe worlds. It can be found [here](https://github.com/Builderb0y/BigGlobe/blob/scriptable-generators/docs/tutorials/Structures.md).
