### ISSUE TITLE
Generating structures too often(Fabric 1.20.1)

### ISSUE THREAD

**Issue by GrinNik** [Builderb0y/BigGlobe#54]
Fabric - 0.16.7
Big Globe - 4.5.0
![изображение](https://github.com/user-attachments/assets/e94372ba-b644-4a38-9ede-670f42d19db6) 
(And that's just what got into the frame, there are a couple more behind the scenes)

There are no other mods for generation

Is there a way to customize the spawn frequency or disable it?

**Comment by Builderb0y** [comment]
You can customize the frequency of all structures with data packs. I initially set the spawn frequency of mega dungeons and geodes high because they spawned at a wide range of Y levels, but since then I think mega dungeons are now restricted to spawning at cave Y levels, so I can probably reduce their frequency a bit in the next version.
