### ISSUE TITLE
Is it possible to make the biomes from the mod support in Big Globe?

### ISSUE THREAD

**Issue by Zoor-Github** [Builderb0y/BigGlobe#56]
I want to add biomes from the mod. Can you tell me if it is possible and how to do it? I saw in the description about support for mods with data packs. Can you tell me how to do it? (Mod Regions Unexplored)

**Comment by Builderb0y** [comment]
You'll need to find a spot to put them somewhere in the decision tree responsible for computing biomes. I have a little bit of documentation on decision trees [here](https://github.com/Builderb0y/BigGlobe/blob/scriptable-generators/scripting%20docs/files/data/modid/worldgen/bigglobe_decision_tree/Decision%20Trees.md). I would also recommend getting familliar with [column values](https://github.com/Builderb0y/BigGlobe/tree/scriptable-generators/scripting%20docs/files/data/modid/worldgen/bigglobe_column_value), since decision trees make heavy use of them.

**Comment by Zoor-Github** [comment]
Thanks.

**Comment by Zoor-Github** [comment]
Do you have any example of such a datapack?

**Comment by Builderb0y** [comment]
Not really, since every biome-adding mod people have requested support for so far has had *way* more biomes than I wanted to deal with.

**Comment by Zoor-Github** [comment]
Okay, that's too bad. Then if I make a datapack, I'll probably publish it on Modrinth. I asked about them because I'm very bad at understanding text without examples

**Comment by AstralDestiny** [comment]
Would take a copy where it's just vanilla for the heights for overworld/nether/end Though not fully sure how complex that would be if any.

**Comment by Builderb0y** [comment]
That kind of defeats the whole point of the mod, so I will not be doing that. If anyone else wants to, feel free.
