### ISSUE TITLE
[Request] Artifacts mod support

### ISSUE THREAD

**Issue by SweetSnowyWitch** [Builderb0y/BigGlobe#64]
Hello, is it possible to add [Artifacts mod](https://modrinth.com/mod/artifacts) support? 
I've tried to do this myself on Fabric 1.20.1, but datapack couldn't load tag:
```
[22:13:11] [Worker-Main-17/ERROR]: Couldn't load tag bigglobe:overworld/large_features as it is missing following references: artifacts:campsite (from file/Big-Globe-Artifacts-Compat_1.20.1)
``` 

How can I add mod worldgen configurated and placed features to Big Globe world generation?

**Comment by Builderb0y** [comment]
The modrinth page for that mod claims that the campsite is a structure, not a feature. So you need to add big globe's biomes to the tag that the structure spawns in, instead of putting it in a feature dispatcher.

**Comment by SweetSnowyWitch** [comment]
I've checked it once more. It's definetly feature.

![изображение](https://github.com/user-attachments/assets/0b4717c5-b122-4e7d-a189-acfe09781516)

**Comment by Builderb0y** [comment]
So the modrinth page is incorrect then. In this case, you'll need to actually write a script to place the feature, and then add that script to the feature dispatcher tag. The "small_dungeons" feature dispatcher is probably closest to what you'd want, you'd just need to make an alternate version which places campsites instead of whatever the cave system specifies.
